services:
  borgmatic:
    container_name: borg-restore
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${VOLUME_RESTORE}:/restore
    security_opt:
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/fuse:/dev/fuse
    command: /bin/sh
